name: Check

on:
  push:
    branches:
      - '*'

jobs:
  check-name:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Check Repository Name
        run: |
          IFS='/' read -r username repository <<< ${{ github.repository }}
          if [[ "$repository" =~ "a-project-name" ]]; then
          echo "Repository name is not allowed, failing workflow."
          exit 1

  
