name: Valid repository name

on:
  push:
    branches:
      - '*'

jobs:
  check-name:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Check Repository Name
        run: |
          if [[ ! "${{ github.repository }}" ~= "BTS-ABT\/ai-academy-[a-z-]*-repository" ]]; then
            echo "Repository name is not allowed. Please rename your repository to "ai-academy-*team project name*-repository"."
            exit 1
          fi
