name: Check

on:
  push:
    branches:
      - '*'

jobs:
  check-name:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Check Repository Name
        if: 1 != 2
        run: |
          echo "::error file={name},line={line},endLine={endLine},title={title}::{message}"
          exit 1
