name: Valid repository name

on:
  push:
    branches:
      - '*'

jobs:
  check-name:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Check Repository Name
        run: |
          if [[ "${{ github.repository }}" != "${{ github.repository_owner }}/ai-academy-${{ github.repository_owner }}-repository" ]]; then
            echo "Repository name "${repository}" is not allowed. Please rename your repository to "ai-academy-
            exit 1
          fi
